/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ContactForm = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'organization' : IDL.Text,
});
export const Time = IDL.Int;
export const PersistentContact = IDL.Record({
  'id' : IDL.Nat,
  'contactForm' : ContactForm,
  'submittedAt' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllContacts' : IDL.Func([], [IDL.Vec(PersistentContact)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContact' : IDL.Func([IDL.Nat], [PersistentContact], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveContact' : IDL.Func([ContactForm], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ContactForm = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'organization' : IDL.Text,
  });
  const Time = IDL.Int;
  const PersistentContact = IDL.Record({
    'id' : IDL.Nat,
    'contactForm' : ContactForm,
    'submittedAt' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllContacts' : IDL.Func([], [IDL.Vec(PersistentContact)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContact' : IDL.Func([IDL.Nat], [PersistentContact], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveContact' : IDL.Func([ContactForm], [], []),
  });
};

export const init = ({ IDL }) => { return []; };